version: '2'
services:
  mongo:
    image: mongo
    command:
      - --smallfiles
    expose:
      - "27017"
    volumes:
      - "~/data/mongo:/data/db"
    restart: always
  uptime:
    image: katsanva/uptime
    ports:
      - 80:8082
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - default
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - SERVICE_USERNAME=root
      - SERVICE_PASSWORD=pass
